/**
 * Script to test WebSocket connections with Socket.io
 */
const { io } = require('socket.io-client');

// Module name for logging
const ModuleName = '[socket-test]';

// Real JWT token generated by generate-test-token.js
const token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4LTEyMzQtMTIzNC0xMjM0LTEyMzQ1Njc4OTAxMiIsInBob25lTnVtYmVyIjoiKzE1NTU1NTU1NTU1IiwiaWF0IjoxNzQ4NjQ0MTMxfQ.Cj1yZBk6-2hgu1YKr-SfPjUWXoXtCdqOaf7Ft4iMKR0';

// Server URL
const serverUrl = 'http://localhost:3000';

console.log(`${ModuleName} Connecting to server: ${serverUrl}`);
console.log(`${ModuleName} Waiting for notifications for 60 seconds...`);
console.log(`${ModuleName} Press Ctrl+C to exit early`);

// Create Socket.io client
const socket = io(serverUrl, {
  auth: {
    token: token
  }
});

// Connection events
socket.on('connect', () => {
  console.log(`${ModuleName} Connected to server with ID: ${socket.id}`);
  
  // Test ping-pong
  socket.emit('ping', (response) => {
    console.log(`${ModuleName} Ping response:`, response);
    console.log(`${ModuleName} Socket connection established and verified`);
    console.log(`${ModuleName} Listening for notifications...`);
  });
});

// Handle notifications
socket.on('notification', (notification) => {
  console.log(`\n${ModuleName} ✉️ RECEIVED NOTIFICATION ✉️`);
  console.log(`${ModuleName} Type: ${notification.type}`);
  console.log(`${ModuleName} Timestamp: ${new Date(notification.createdAt).toLocaleString()}`);
  console.log(`${ModuleName} Data:`, JSON.stringify(notification.data, null, 2));
  console.log(`${ModuleName} ---------------------------------`);
});

// Error handling
socket.on('connect_error', (error) => {
  console.error(`${ModuleName} Connection error:`, error.message);
  process.exit(1);
});

// Disconnection
socket.on('disconnect', (reason) => {
  console.log(`${ModuleName} Disconnected: ${reason}`);
});

// Set timeout for connection - stay connected for 60 seconds
const timeout = setTimeout(() => {
  console.log(`\n${ModuleName} Test completed - 60 seconds elapsed`);
  socket.disconnect();
  process.exit(0);
}, 60000);

// Cleanup on exit
process.on('SIGINT', () => {
  console.log(`\n${ModuleName} Process interrupted, cleaning up...`);
  clearTimeout(timeout);
  socket.disconnect();
  process.exit(0);
}); 